### ISSUE TITLE
Travis build failed [HW-3]

### ISSUE THREAD

**Issue by 21011996** [dboulytchev/compiler-workout#159]
Hopefully you could clarify what could cause `Error: Cannot find file re_str.cmxa` in Travis build. Is it my code or something wrong with settings? #158 
I was able to successfully build and test code locally.

**Comment by agordeevw** [comment]
ocaml-rp package suddenly updated a few days ago and moved required files to different places.
To fix: in the file 'src/Makefile' change the line
```
-LIBS = GT.cma unix.cma re.cma re_emacs.cma re_str.cma
```

to 

```
+LIBS = GT.cma unix.cma re.cma emacs/re_emacs.cma str/re_str.cma
```

**Comment by anlun** [comment]
Спасибо за описание проблемы и решение её. Теперь мы зафиксируем версии библиотек (уже в master), чтобы такого больше не происходило.

**Comment by dimatomp** [comment]
Похожая проблема ещё остаётся в hw2 - например, #249

**Comment by anlun** [comment]
@dimatomp Я залью эти изменения в hw2. Вы можете после этого с ней смержиться, либо просто добавить соответствующие изменения самостоятельно.

**Comment by dimatomp** [comment]
На всякий случай: если имелся в виду `a94dbcff`, то там ещё в `regression/Makefile` это надо добавить. У себя сделал

**Comment by anlun** [comment]
Действительно, спасибо. Обновил hw2.
